import { useEffect, useRef, useState } from "react";
import { api } from "../lib/bridge";
import type { AiDerivative, AiEnhancementHealth, AiEnhancementOperation, AiEnhancementPreview, AiEnhancementProgress, AiEnhancementRequest, Asset } from "../types";

type Props={asset:Asset;onClose:()=>void;onChanged:()=>void;onOpenParent:(assetId:string)=>void};

export function AiEnhanceDialog({asset,onClose,onChanged,onOpenParent}:Props){
  const dialogRef=useRef<HTMLElement>(null);const [operation,setOperation]=useState<AiEnhancementOperation>("denoise");const [scale,setScale]=useState<1|2|4>(1);const [region,setRegion]=useState({x:.375,y:.375,width:.25,height:.25});const [reviewZoom,setReviewZoom]=useState(100);const [health,setHealth]=useState<AiEnhancementHealth|null>(null);const [existing,setExisting]=useState<AiDerivative|null>(null);const [preview,setPreview]=useState<AiEnhancementPreview|null>(null);const [progress,setProgress]=useState<AiEnhancementProgress|null>(null);const [busy,setBusy]=useState<"install"|"preview"|"apply"|null>(null);const [installProgress,setInstallProgress]=useState<{receivedBytes:number;totalBytes:number}|null>(null);const [slowCpu,setSlowCpu]=useState(false);const [error,setError]=useState<string|null>(null);
  const refresh=()=>Promise.all([api.aiEnhancementHealth(),api.aiDerivative(asset.id)]).then(([nextHealth,derivative])=>{setHealth(nextHealth);setExisting(derivative);});
  useEffect(()=>{let active=true;let unlisten:(()=>void)|undefined;void refresh().catch(reason=>active&&setError(String(reason)));void api.onAiEnhancementProgress(value=>active&&value.assetId===asset.id&&setProgress(value)).then(remove=>{if(active)unlisten=remove;else remove();});dialogRef.current?.focus();return()=>{active=false;unlisten?.();void api.cancelAiEnhancementPreview();};},[asset.id]);
  useEffect(()=>{setScale(operation==="denoise"?1:4);setPreview(null);setProgress(null);},[operation]);
  const selectedModel=health?.models.find(model=>model.operation===operation);const request=(includeRegion:boolean):AiEnhancementRequest=>({assetId:asset.id,operation,targetScale:scale,previewRegion:includeRegion?region:undefined,allowSlowCpuFallback:slowCpu});
  const install=async()=>{setBusy("install");setError(null);try{setHealth(await api.installAiEnhancementModel(operation,value=>setInstallProgress(value)));}catch(reason){setError(String(reason));}finally{setBusy(null);}};
  const runPreview=async()=>{setBusy("preview");setError(null);setProgress({assetId:asset.id,current:0,total:1,stage:"Preparing preview"});try{setPreview(await api.previewAiEnhancement(request(true)));setProgress({assetId:asset.id,current:1,total:1,stage:"Preview ready"});}catch(reason){setError(String(reason));}finally{setBusy(null);}};
  const apply=async()=>{setBusy("apply");setError(null);setProgress({assetId:asset.id,current:0,total:1,stage:"Preparing full-resolution source"});try{const derivative=await api.applyAiEnhancement(request(false));setExisting(derivative);setPreview(null);onChanged();}catch(reason){setError(String(reason));}finally{setBusy(null);}};
  const remove=async()=>{if(!existing||!window.confirm("Delete this managed AI derivative? Its parent source and all protected originals remain untouched."))return;setBusy("apply");setError(null);try{const parent=await api.deleteAiDerivative(existing.assetId);setExisting(null);onChanged();onOpenParent(parent);}catch(reason){setError(String(reason));}finally{setBusy(null);}};
  const cancel=()=>{if(busy==="install")void api.cancelAiEnhancementModelInstall();else if(busy==="preview")void api.cancelAiEnhancementPreview();else if(busy==="apply")void api.cancelAiEnhancement(asset.id);};
  return <div className="modal-backdrop" role="presentation"><section ref={dialogRef} tabIndex={-1} className="modal ai-enhance-dialog" role="dialog" aria-modal="true" aria-labelledby="ai-enhance-title" onKeyDown={event=>{if(event.key==="Escape"&&!busy)onClose();}}>
    <button className="modal-close" aria-label="Close AI Enhance" disabled={Boolean(busy)} onClick={onClose}>×</button><header><span className="eyebrow">Local full-resolution processing</span><h2 id="ai-enhance-title">AI Enhance</h2><p>The original is never overwritten. Apply creates a new lossless managed master with explicit source lineage.</p></header>
    <div className="ai-enhance-layout"><section className="ai-enhance-settings"><fieldset><legend>Operation</legend><div className="ai-enhance-tabs"><button className={operation==="denoise"?"active":""} onClick={()=>setOperation("denoise")}>AI Denoise</button><button className={operation==="super_resolution"?"active":""} onClick={()=>setOperation("super_resolution")}>Super Resolution</button></div>{operation==="super_resolution"?<label>Output scale<select value={scale} onChange={event=>setScale(Number(event.target.value) as 2|4)}><option value={2}>2×</option><option value={4}>4×</option></select></label>:<p>Noise reduction preserves the source dimensions.</p>}</fieldset>
      <fieldset><legend>Preview region</legend><label>Horizontal position<input aria-label="Preview horizontal position" type="range" min="0" max="0.75" step="0.01" value={region.x} onChange={event=>setRegion(value=>({...value,x:Number(event.target.value)}))}/></label><label>Vertical position<input aria-label="Preview vertical position" type="range" min="0" max="0.75" step="0.01" value={region.y} onChange={event=>setRegion(value=>({...value,y:Number(event.target.value)}))}/></label><small>The movable 25% selection is capped at 1024 × 1024 pixels for responsive inference. Apply always processes the entire authoritative source.</small></fieldset>
      <fieldset><legend>Local model</legend>{selectedModel?<><strong>{selectedModel.model}</strong><small>{selectedModel.licence} · {selectedModel.installed?selectedModel.executionProvider:"Not installed"}</small><small>{(selectedModel.approximateBytes/1_000_000).toFixed(0)} MB · {selectedModel.modelRevision}</small><small>Expected speed: {health?.cudaAvailable?"fast preview; full-image time varies with dimensions and tile count":"slow on CPU; large images may be impractical"}.</small>{!selectedModel.installed?<button className="primary-button" disabled={Boolean(busy)} onClick={()=>void install()}>Install verified model</button>:null}</>:<p>Checking the local runtime…</p>}{installProgress?<progress max={installProgress.totalBytes} value={installProgress.receivedBytes}/>:null}<label className="ai-cpu-option"><input type="checkbox" checked={slowCpu} onChange={event=>setSlowCpu(event.target.checked)}/> Allow slow CPU retry after bounded GPU out-of-memory retries</label></fieldset>
    </section><section className="ai-enhance-review" aria-label="Enhancement comparison">{preview?<><label className="ai-review-zoom">Review zoom <input aria-label="Review zoom" type="range" min="100" max="200" step="10" value={reviewZoom} onChange={event=>setReviewZoom(Number(event.target.value))}/><output>{reviewZoom}%</output></label><div className="ai-compare"><figure><figcaption>Before · source crop</figcaption><div><img style={{transform:`scale(${reviewZoom/100})`}} src={preview.beforeUrl} alt="Source preview crop"/></div></figure><figure><figcaption>After · {operation==="denoise"?"denoised":"super resolved"}</figcaption><div><img style={{transform:`scale(${reviewZoom/100})`}} src={preview.afterUrl} alt="AI enhancement preview"/></div></figure></div></>:<div className="ai-enhance-placeholder"><img src={asset.previewUrl} alt={asset.filename}/><p>Choose an operation, install its pinned model if needed, then generate a review crop.</p></div>}{preview?<dl className="ai-provenance"><div><dt>Provider</dt><dd>{preview.provenance.model}</dd></div><div><dt>Execution</dt><dd>{preview.provenance.executionProvider}</dd></div><div><dt>Tiles</dt><dd>{preview.provenance.tileSize}px + {preview.provenance.overlap}px overlap</dd></div><div><dt>Inference</dt><dd>{preview.provenance.timings.inferenceMs} ms</dd></div></dl>:null}</section></div>
    {existing?<section className="ai-existing"><strong>Current derived master: {existing.displayName}</strong><span>{existing.width} × {existing.height} · {existing.provenance.model}</span><div><button onClick={()=>onOpenParent(existing.parentAssetId)}>Compare / open parent</button><button disabled={Boolean(busy)} onClick={()=>void runPreview()}>Re-generate preview</button><button className="danger" disabled={Boolean(busy)} onClick={()=>void remove()}>Delete derivative</button></div></section>:null}
    {progress?<div className="ai-progress" aria-live="polite"><progress max={Math.max(1,progress.total)} value={progress.current}/><span>{progress.stage} · {progress.current} of {progress.total}</span></div>:null}{error?<p className="develop-error" role="alert">AI Enhance: {error}</p>:null}
    <div className="modal-actions"><button disabled={!busy} onClick={cancel}>Cancel task</button><button disabled={Boolean(busy)||!selectedModel?.installed} onClick={()=>void runPreview()}>{busy==="preview"?"Previewing…":"Preview crop"}</button><button className="primary-button" disabled={Boolean(busy)||!selectedModel?.installed||!preview} onClick={()=>void apply()}>{busy==="apply"?"Processing…":"Apply full enhancement"}</button></div><p className="ai-honesty">Accepted output is 8-bit sRGB lossless PNG in this build. The current Develop recipe is copied to the new physical source; masks remain editable and downstream.</p>
  </section></div>;
}
