import { useEffect, useRef, useState } from "react";
import { defaultExportConfig, api } from "../lib/bridge";
import type { Asset, DevelopRecipe, ExportBatchReport, ExportConfig, ExportPreset, ExportProgress } from "../types";

type Props = { assets: Asset[]; selected: Asset; initialAssetIds?: string[]; onClose: () => void };

function dimensions(asset: Asset, recipe: DevelopRecipe | undefined, config: ExportConfig) {
  let width=asset.width ?? 0; let height=asset.height ?? 0;
  if (recipe && width && height) { width=Math.max(1,Math.round(width*recipe.settings.cropWidth));height=Math.max(1,Math.round(height*recipe.settings.cropHeight));if(Math.abs(recipe.settings.rotateQuadrants)%2===1)[width,height]=[height,width]; }
  if (!width || !height) return null;
  let scale=1;
  if(config.resizeMode==="bounds")scale=Math.min(config.width/width,config.height/height);
  if(config.resizeMode==="longedge")scale=config.width/Math.max(width,height);
  if(config.resizeMode==="shortedge")scale=config.width/Math.min(width,height);
  if(config.resizeMode==="percentage")scale=config.percentage/100;
  if(config.noEnlarge)scale=Math.min(1,scale);
  return [Math.max(1,Math.round(width*scale)),Math.max(1,Math.round(height*scale))] as const;
}

export function ExportDialog({ assets, selected, initialAssetIds, onClose }: Props) {
  const dialogRef=useRef<HTMLElement>(null);
  const [queued,setQueued]=useState<string[]>(initialAssetIds?.length?[...new Set(initialAssetIds)]:[selected.id]); const [config,setConfig]=useState<ExportConfig>(defaultExportConfig()); const [destination,setDestination]=useState("");
  const [presets,setPresets]=useState<ExportPreset[]>([]); const [presetId,setPresetId]=useState("full-jpeg"); const [recipes,setRecipes]=useState<Record<string,DevelopRecipe>>({});
  const [running,setRunning]=useState(false); const [progress,setProgress]=useState<ExportProgress|null>(null); const [report,setReport]=useState<ExportBatchReport|null>(null); const [error,setError]=useState<string|null>(null);
  const update=<K extends keyof ExportConfig>(key:K,value:ExportConfig[K])=>setConfig(current=>({...current,[key]:value}));
  useEffect(()=>{let active=true;void api.exportPresets().then(values=>{if(!active)return;setPresets(values);const preset=values.find(value=>value.id==="full-jpeg");if(preset)setConfig(preset.config);}).catch(reason=>active&&setError(String(reason)));return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;void Promise.all(queued.map(async id=>[id,await api.getDevelopRecipe(id)] as const)).then(values=>{if(active)setRecipes(Object.fromEntries(values));});return()=>{active=false;};},[queued]);
  useEffect(()=>{let unlisten:(()=>void)|undefined;void api.onExportProgress(setProgress).then(value=>{unlisten=value;});return()=>unlisten?.();},[]);
  useEffect(()=>dialogRef.current?.focus(),[]);
  const first=assets.find(asset=>asset.id===queued[0]);const estimate=first?dimensions(first,recipes[first.id],config):null;
  const filenamePreview=first?config.filenameTemplate.replaceAll("{filename}",first.filename).replaceAll("{stem}",first.filename.replace(/\.[^.]+$/,"")).replaceAll("{sequence}",String(config.sequenceStart).padStart(config.sequencePadding,"0")).replaceAll("{capturedate}",first.capturedAt.slice(0,10)).replaceAll("{exportdate}",new Date().toISOString().slice(0,10)).replaceAll("{rating}","0").replaceAll("{custom}",config.customText)+({jpeg:".jpg",png:".png",tiff:".tif"}[config.format]):"—";
  const refresh=()=>api.exportPresets().then(setPresets);
  const run=async()=>{setError(null);setReport(null);let folder=destination;if(!folder){folder=await api.chooseExportFolder()??"";if(!folder)return;setDestination(folder);}setRunning(true);setProgress({batchId:"pending",current:0,completed:0,total:queued.length,phase:"Waiting"});try{const completed=await api.startExportBatch(queued,folder,config);setReport(completed);const phase=completed.cancelled===completed.requested?"Cancelled":completed.failed===completed.requested?"Failed":"Complete";setProgress({batchId:completed.batchId,current:completed.requested,completed:completed.complete,total:completed.requested,phase,file:"Export report ready.",failures:completed.failed,cancelled:completed.cancelled,skipped:completed.skipped});}catch(reason){const message=String(reason);setError(message);setProgress(current=>({batchId:current?.batchId??"failed",current:current?.current??0,completed:current?.completed??0,total:current?.total??queued.length,phase:"Failed",file:message}));}finally{setRunning(false);}};
  const savePreset=async(duplicate=false)=>{const current=presets.find(value=>value.id===presetId);const name=window.prompt(duplicate?"Name the duplicate output preset":"Name this output preset",duplicate&&current?`${current.name} copy`:"My output preset")?.trim();if(!name)return;await api.saveExportPreset({id:duplicate?crypto.randomUUID():current&&!current.builtIn?current.id:crypto.randomUUID(),name,builtIn:false,config});await refresh();};
  return <div className="modal-backdrop" role="presentation"><section ref={dialogRef} tabIndex={-1} onKeyDown={event=>{if(event.key==="Escape"&&!running)onClose();}} className="modal export-dialog" role="dialog" aria-modal="true" aria-labelledby="export-title">
    <button className="modal-close" aria-label="Close export" disabled={running} onClick={onClose}>×</button><header><span className="eyebrow">Full-resolution output</span><h2 id="export-title">Export photographs</h2><p>Every item is re-rendered from its protected full-resolution source with its own accepted Develop recipe and masks.</p></header>
    <div className="export-layout"><div className="export-settings">
      <fieldset><legend>Export preset</legend><div className="export-row"><select aria-label="Output preset" value={presetId} onChange={event=>{setPresetId(event.target.value);const preset=presets.find(value=>value.id===event.target.value);if(preset)setConfig(preset.config);}}>{presets.map(preset=><option key={preset.id} value={preset.id}>{preset.name}{preset.builtIn?" · built-in":""}</option>)}</select><button type="button" onClick={()=>void savePreset(false)}>Save</button><button type="button" onClick={()=>void savePreset(true)}>Duplicate</button></div><div className="export-row"><button type="button" onClick={()=>void api.importExportPreset().then(value=>value&&refresh())}>Import</button><button type="button" onClick={()=>void api.exportExportPreset(presetId)}>Export preset</button>{!presets.find(value=>value.id===presetId)?.builtIn?<button type="button" onClick={()=>void api.deleteExportPreset(presetId).then(refresh)}>Delete</button>:null}</div></fieldset>
      <fieldset><legend>Queue</legend><p>{queued.length} photographs selected ({queued.filter(id=>assets.some(asset=>asset.id===id)).length} currently loaded). Export runs one item at a time to bound memory.</p><div className="export-queue-picker">{assets.map(asset=><label key={asset.id}><input type="checkbox" checked={queued.includes(asset.id)} onChange={()=>setQueued(current=>current.includes(asset.id)?current.filter(id=>id!==asset.id):[...current,asset.id])}/><span>{asset.filename}</span><small>{asset.hasEdits?"Developed":"As shot"}</small></label>)}</div></fieldset>
      <fieldset><legend>File settings</legend><div className="export-grid"><label>Format<select value={config.format} onChange={event=>update("format",event.target.value as ExportConfig["format"])}><option value="jpeg">JPEG</option><option value="png">PNG</option><option value="tiff">TIFF</option></select></label>{config.format==="jpeg"?<label>JPEG quality<input type="number" min="1" max="100" value={config.jpegQuality} onChange={event=>update("jpegQuality",Number(event.target.value))}/></label>:null}{config.format==="png"?<label>PNG compression<select value={config.pngCompression} onChange={event=>update("pngCompression",event.target.value as ExportConfig["pngCompression"])}><option value="fast">Fast</option><option value="balanced">Balanced</option><option value="best">Best</option></select></label>:null}<label>Colour space<select value="srgb" disabled><option value="srgb">sRGB with embedded ICC</option></select></label></div>{config.format==="tiff"?<p className="export-honesty">TIFF is 8-bit RGB, uncompressed, with embedded sRGB ICC. This build does not claim 16-bit or compressed TIFF.</p>:null}</fieldset>
      <fieldset><legend>Image sizing</legend><div className="export-grid"><label>Resize<select value={config.resizeMode} onChange={event=>update("resizeMode",event.target.value as ExportConfig["resizeMode"])}><option value="original">Original dimensions</option><option value="bounds">Fit bounding box</option><option value="longedge">Long edge</option><option value="shortedge">Short edge</option><option value="percentage">Percentage</option></select></label>{config.resizeMode==="bounds"?<><label>Maximum width<input type="number" min="1" value={config.width} onChange={event=>update("width",Number(event.target.value))}/></label><label>Maximum height<input type="number" min="1" value={config.height} onChange={event=>update("height",Number(event.target.value))}/></label></>:null}{["longedge","shortedge"].includes(config.resizeMode)?<label>Edge pixels<input type="number" min="1" value={config.width} onChange={event=>update("width",Number(event.target.value))}/></label>:null}{config.resizeMode==="percentage"?<label>Percentage<input type="number" min="1" max="800" value={config.percentage} onChange={event=>update("percentage",Number(event.target.value))}/></label>:null}<label>Resolution metadata (PPI)<input type="number" min="1" max="2400" value={config.ppi} onChange={event=>update("ppi",Number(event.target.value))}/></label><label>Output sharpening<select value={config.sharpening} onChange={event=>update("sharpening",event.target.value as ExportConfig["sharpening"])}><option value="none">None</option><option value="low">Low</option><option value="standard">Standard</option><option value="high">High</option></select></label></div><label className="export-check"><input type="checkbox" checked={config.noEnlarge} onChange={event=>update("noEnlarge",event.target.checked)}/> Do not enlarge smaller photographs</label></fieldset>
      <fieldset><legend>Metadata</legend><div className="export-grid"><label>Include<select value={config.metadata} onChange={event=>update("metadata",event.target.value as ExportConfig["metadata"])}><option value="all">All practical metadata</option><option value="copyrightcontact">Copyright & contact</option><option value="copyright">Copyright only</option><option value="none">None</option></select></label></div>{config.metadata==="all"?<div className="export-checks"><label><input type="checkbox" checked={config.includeKeywords} onChange={event=>update("includeKeywords",event.target.checked)}/> Keywords</label><label><input type="checkbox" checked={config.includeRating} onChange={event=>update("includeRating",event.target.checked)}/> Embedded rating</label><label><input type="checkbox" checked={config.includeLocation} onChange={event=>update("includeLocation",event.target.checked)}/> Location / GPS</label></div>:null}<p>Orientation is normalised to the rendered pixels. Internal ids, paths, recipe JSON, and mask payloads are never added.</p></fieldset>
      <fieldset><legend>Filename & destination</legend><label>Template<input value={config.filenameTemplate} onChange={event=>update("filenameTemplate",event.target.value)}/></label><p className="token-help">Tokens: {'{filename} {stem} {sequence} {capturedate} {exportdate} {rating} {custom}'}</p><div className="export-grid"><label>Custom text<input value={config.customText} onChange={event=>update("customText",event.target.value)}/></label><label>Sequence start<input type="number" min="0" value={config.sequenceStart} onChange={event=>update("sequenceStart",Number(event.target.value))}/></label><label>Padding<input type="number" min="1" max="8" value={config.sequencePadding} onChange={event=>update("sequencePadding",Number(event.target.value))}/></label><label>Existing files<select value={config.collision} onChange={event=>update("collision",event.target.value as ExportConfig["collision"])}><option value="unique">Create unique name</option><option value="skip">Skip</option><option value="replace">Replace safely</option><option value="ask">Ask / stop at conflict</option></select></label></div><button type="button" onClick={()=>void api.chooseExportFolder().then(value=>value&&setDestination(value))}>Choose folder</button><output className="export-path">{destination||"No destination chosen"}</output></fieldset>
    </div><aside className="export-summary"><h3>Output summary</h3>{first?<><strong>{first.filename}</strong><dl><div><dt>Estimated dimensions</dt><dd>{estimate?`${estimate[0]} × ${estimate[1]}`:"Read during export"}</dd></div><div><dt>Megapixels</dt><dd>{estimate?`${(estimate[0]*estimate[1]/1_000_000).toFixed(1)} MP`:"—"}</dd></div><div><dt>Format</dt><dd>{config.format.toUpperCase()}</dd></div><div><dt>Colour</dt><dd>sRGB + ICC</dd></div><div><dt>Metadata</dt><dd>{config.metadata}{config.includeLocation&&config.metadata==="all"?" + GPS":" · no GPS"}</dd></div><div><dt>Filename</dt><dd>{filenamePreview}</dd></div></dl><p>File size is estimated only after encoding; content and metadata affect it.</p></>:null}
      {progress?<div className="export-progress" aria-live="polite"><strong>{progress.phase}</strong><span>{progress.completed} complete of {progress.total}</span><progress max={Math.max(1,progress.total)} value={progress.current}/><small>{progress.file??"Preparing safe output…"}</small></div>:null}
      {report?<section className="export-result" aria-label="Export result"><h3>{report.complete} complete</h3><p>{report.failed} failed · {report.skipped} skipped · {report.cancelled} cancelled</p><p>{(report.elapsedMs/1000).toFixed(1)} s · concurrency {report.concurrency}</p><button type="button" onClick={()=>void api.revealExport(report.destination)}>Open folder</button><div>{report.items.map(item=><p key={item.assetId} className={`export-item ${item.state}`}><strong>{item.filename||item.assetId}</strong><span>{item.state}{item.width?` · ${item.width}×${item.height}`:""}</span>{item.error?<small>{item.error}</small>:null}</p>)}</div></section>:null}
      {error?<p className="develop-error" role="alert">Export: {error}</p>:null}<div className="export-actions">{running?<button type="button" onClick={()=>void api.cancelExportBatch()}>Cancel current & remaining</button>:<button className="primary-button" type="button" disabled={!queued.length} onClick={()=>void run()}>Export {queued.length} photograph{queued.length===1?"":"s"}</button>}</div>
    </aside></div>
  </section></div>;
}
