import { BrainCircuit, Images, Layers3, Pause, Play, RefreshCw, Search, Sparkles, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { api } from "../lib/bridge";
import type { Asset, AssetFilter, DiscoveryGroup, SemanticIndexStatus, SemanticSearchResult, SmartCollectionProposal, SmartRule } from "../types";
import type { LibraryLayout } from "../views/LibraryProductivityView";

type Props={active:Asset|null;filter:AssetFilter;selectedIds:ReadonlySet<string>;onResults:(results:SemanticSearchResult[],label:string)=>Promise<void>|void;onClear:()=>void;onLayout:(layout:LibraryLayout)=>void;onChanged:()=>Promise<void>|void;onNotice:(message:string)=>void};
type Section="search"|"similar"|"duplicates"|"suggestions"|"smart";
const formatBytes=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(1)} GB`:`${(bytes/1024**2).toFixed(1)} MB`;

export function SemanticDiscovery({active,filter,selectedIds,onResults,onClear,onLayout,onChanged,onNotice}:Props){
  const [open,setOpen]=useState(true);const [section,setSection]=useState<Section>("search");const [status,setStatus]=useState<SemanticIndexStatus|null>(null);const [query,setQuery]=useState("");const [searched,setSearched]=useState(false);const [loading,setLoading]=useState(false);const [resultMeta,setResultMeta]=useState<SemanticSearchResult[]>([]);const [groups,setGroups]=useState<DiscoveryGroup[]>([]);const [proposalInput,setProposalInput]=useState("4 stars or higher taken with the Nikon in 2025");const [proposal,setProposal]=useState<SmartCollectionProposal|null>(null);const [installProgress,setInstallProgress]=useState<{receivedBytes:number;totalBytes:number;file:string}|null>(null);const request=useRef(0);
  const refresh=async()=>setStatus(await api.semanticIndexStatus());
  useEffect(()=>{void refresh();let active=true;const cleanups:Array<()=>void>=[];Promise.all([api.onSemanticInstallProgress(value=>active&&setInstallProgress(value)),api.onSemanticIndexProgress(()=>active&&void refresh())]).then(values=>active?cleanups.push(...values):values.forEach(stop=>stop()));return()=>{active=false;cleanups.forEach(stop=>stop());};},[]);
  useEffect(()=>{if(selectedIds.size)void api.prioritiseSemanticSources([...selectedIds]);},[selectedIds]);
  const deterministicFilter=useMemo(()=>({ratingMin:filter.rating,decision:filter.decision==="all"?undefined:filter.decision,fileType:filter.fileType,edited:filter.edited,dateFrom:filter.dateFrom,dateTo:filter.dateTo,collectionId:filter.collectionId}),[filter]);
  const runSearch=async()=>{const value=query.trim();if(!value)return;const id=++request.current;setLoading(true);setSearched(false);try{const response=await api.semanticSearch({query:value,limit:80,semanticWeight:.85,filter:deterministicFilter});if(id!==request.current)return;setResultMeta(response.results);setSearched(true);await onResults(response.results,`Semantic: ${value}`);onNotice(`${response.results.length} source-level semantic matches · ${response.executionProvider}. Similarity is not a probability.`);}catch(error){if(id===request.current)onNotice(`Semantic search unavailable: ${String(error)}`);}finally{if(id===request.current)setLoading(false);}};
  const findSimilar=async()=>{if(!active)return;setLoading(true);try{const results=await api.findSimilarSources(active.id);setResultMeta(results);await onResults(results,`Similar to ${active.filename}`);onNotice(`${results.length} related sources ranked by local image similarity.`);}catch(error){onNotice(`Find Similar unavailable: ${String(error)}`);}finally{setLoading(false);}};
  const loadGroups=async(kind:"duplicates"|"suggestions")=>{setLoading(true);try{setGroups((await api.discoverSemanticGroups(kind)).filter(group=>!group.dismissed));}catch(error){onNotice(`Discovery unavailable: ${String(error)}`);}finally{setLoading(false);}};
  useEffect(()=>{if(section==="duplicates"||section==="suggestions")void loadGroups(section);},[section]);
  const dismiss=async(group:DiscoveryGroup)=>{await api.decideSemanticSuggestion(group,"dismissed");setGroups(values=>values.filter(value=>value.id!==group.id));onNotice("Suggestion dismissed locally. No photo metadata changed.");};
  const acceptStack=async(group:DiscoveryGroup)=>{if(group.assetIds.length<2)return;const stack=await api.createStack(group.assetIds,group.assetIds[0]);await api.decideSemanticSuggestion(group,"accepted");await onChanged();setGroups(values=>values.filter(value=>value.id!==group.id));onNotice(`Suggestion accepted as normal stack ${stack}. Ratings, keywords and files were not changed.`);};
  const previewGroup=async(group:DiscoveryGroup)=>{const results=group.assetIds.map((assetId,index)=>({assetId,sourceId:group.sourceIds[index]??assetId,score:group.score,semanticScore:group.score,metadataScore:0,strength:group.kind==="exact_duplicate"?"Exact duplicate":"Strong match",explanation:[group.explanation],missing:false}));await onResults(results,group.kind.replaceAll("_"," "));onLayout(group.assetIds.length===2?"compare":"survey");};
  const install=async()=>{if(!window.confirm("Install Google SigLIP base patch16/224? Keepframe will download about 778 MB from Hugging Face into D:\\AI Models\\Keepframe\\semantic. The Apache-2.0 model is optional and cancellation leaves photographs untouched."))return;setLoading(true);try{setStatus(await api.installSemanticModel(setInstallProgress));onNotice("Semantic model installed and checksum verified. Indexing starts only when requested.");}catch(error){onNotice(`Semantic model installation failed: ${String(error)}`);}finally{setLoading(false);setInstallProgress(null);}};
  const startIndex=async(rebuild=false)=>{if(rebuild&&!window.confirm("Rebuild the derived semantic index? Catalogue metadata, Collections, stacks and photographs are not changed."))return;setLoading(true);try{setStatus(await api.startSemanticIndex(rebuild));onNotice("Semantic indexing reached a safe stopping point.");}catch(error){onNotice(`Semantic indexing unavailable: ${String(error)}`);}finally{setLoading(false);}};
  const updateRule=(index:number,patch:Partial<SmartRule>)=>setProposal(value=>value?{...value,rules:value.rules.map((rule,position)=>position===index?{...rule,...patch}:rule)}:value);
  const saveProposal=async()=>{if(!proposal)return;await api.saveCollection({name:proposal.name.trim()||"Smart proposal",kind:"smart",matchMode:proposal.matchMode,rules:proposal.rules});await onChanged();setProposal(null);onNotice("Smart Collection created only after your explicit save.");};
  return <section className={open?"semantic-discovery open":"semantic-discovery"} aria-label="Semantic discovery">
    <header><button className="semantic-title" onClick={()=>setOpen(value=>!value)}><BrainCircuit size={18}/><span><strong>Local Discovery</strong><small>{status?.detail??"Checking local semantic index…"}</small></span></button>{status?<span className={status.available?"semantic-ready":"semantic-unavailable"}>{status.available?`${status.indexedSources}/${status.totalSources} indexed`:"Optional model"}</span>:null}</header>
    {open?<><nav aria-label="Discovery sections">{([['search','Search',Search],['similar','Similar',Images],['duplicates','Duplicates',Layers3],['suggestions','Suggestions',Sparkles],['smart','Smart proposal',BrainCircuit]] as const).map(([id,label,Icon])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}><Icon size={14}/>{label}</button>)}</nav>
      <div className="semantic-body">
        {!status?.installed?<div className="semantic-install"><p><strong>Google SigLIP base patch16/224</strong> · Apache-2.0 · 768 dimensions · 224 px · about 778 MB. Photos, vectors and queries stay on this computer.</p><button disabled={loading} onClick={()=>void install()}>Install local model…</button>{installProgress?<><progress max={installProgress.totalBytes} value={installProgress.receivedBytes}/><small>{installProgress.file} · {formatBytes(installProgress.receivedBytes)} of {formatBytes(installProgress.totalBytes)}</small><button onClick={()=>void api.cancelSemanticModelInstall()}>Cancel</button></>:null}</div>:<div className="semantic-index-controls"><span>{status.detail}</span><button disabled={loading||status.busy||(!status.paused&&status.queuedSources===0)} onClick={()=>void startIndex(false)}><Play size={13}/> {status.paused?"Resume":status.queuedSources?"Index missing":"Index ready"}</button><button disabled={loading||status.paused||!status.busy} onClick={()=>void api.pauseSemanticIndex().then(refresh)}><Pause size={13}/> Pause</button><button disabled={loading||!status.busy} onClick={()=>void api.cancelSemanticIndex().then(refresh)}><X size={13}/> Cancel</button><button disabled={loading} onClick={()=>void startIndex(true)}><RefreshCw size={13}/> Rebuild</button><small>{formatBytes(status.storageBytes)} vectors · {status.executionProvider}</small></div>}
        {section==="search"?<form className="semantic-search" onSubmit={event=>{event.preventDefault();void runSearch();}}><label><span>Semantic search</span><input aria-label="Semantic search" value={query} maxLength={240} placeholder="dog on a beach" onChange={event=>{setQuery(event.target.value);setSearched(false);void api.cancelSemanticSearch();}}/></label><button className="primary-button" disabled={loading||!query.trim()||!status?.available}>{loading?"Searching…":"Search locally"}</button><button type="button" onClick={()=>{request.current++;setQuery("");setSearched(false);setResultMeta([]);onClear();}}><X size={14}/> Clear</button><small>85% source-image similarity + 15% exact metadata signal. Current Library filters remain deterministic.</small>{resultMeta.length?<ol className="semantic-score-list">{resultMeta.slice(0,5).map(result=><li key={result.assetId}><button onClick={()=>void onResults([result],result.strength)}>{result.strength} · {(result.score*100).toFixed(0)} · {result.explanation.join(" + ")}{result.missing?" · Missing source":""}</button></li>)}</ol>:searched?<p className="semantic-empty">No semantic matches satisfy the current Library filters.</p>:null}</form>:null}
        {section==="similar"?<div className="semantic-action"><p>Find related physical sources using the selected source’s image embedding. Sibling versions are collapsed to one result.</p><button className="primary-button" disabled={loading||!active||!status?.available} onClick={()=>void findSimilar()}>Find Similar to {active?.filename??"selection"}</button></div>:null}
        {section==="duplicates"||section==="suggestions"?<div className="semantic-groups">{groups.length?groups.map(group=><article key={group.id}><strong>{group.kind.replaceAll("_"," ")} · {group.assetIds.length} photographs</strong><span>{group.explanation}</span><small>Similarity {(group.score*100).toFixed(1)} — advisory, not confidence</small><div><button onClick={()=>void previewGroup(group)}>Review in {group.assetIds.length===2?"Compare":"Survey"}</button>{group.kind!=="exact_duplicate"?<button className="primary-button" onClick={()=>void acceptStack(group)}>Accept as stack</button>:null}<button onClick={()=>void dismiss(group)}>Dismiss</button></div></article>):<p className="semantic-empty">{loading?"Checking local index…":section==="duplicates"?"No conservative duplicate groups found.":"No undismissed burst or grouping suggestions."}</p>}</div>:null}
        {section==="smart"?<div className="smart-proposal"><label><span>Describe deterministic catalogue rules</span><input aria-label="Smart Collection request" value={proposalInput} onChange={event=>setProposalInput(event.target.value)}/></label><button disabled={loading||!proposalInput.trim()} onClick={()=>void api.proposeSmartCollectionRules(proposalInput).then(setProposal).catch(error=>onNotice(String(error)))}>Propose rules</button>{proposal?<section><label>Name<input value={proposal.name} onChange={event=>setProposal({...proposal,name:event.target.value})}/></label><p>{proposal.explanation}</p>{proposal.rules.map((rule,index)=><div className="proposal-rule" key={`${rule.field}-${index}`}><strong>{rule.field}</strong><input aria-label={`${rule.field} value`} value={String(rule.value)} onChange={event=>updateRule(index,{value:rule.field==="rating"?Number(event.target.value):event.target.value})}/><code>{rule.operator}</code><button aria-label={`Remove ${rule.field} rule`} onClick={()=>setProposal({...proposal,rules:proposal.rules.filter((_,position)=>position!==index)})}>×</button></div>)}<button className="primary-button" disabled={!proposal.name.trim()||!proposal.rules.length} onClick={()=>void saveProposal()}>Save Smart Collection explicitly</button></section>:null}</div>:null}
      </div></>:null}
  </section>;
}
